name: docker

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: queeg/graphite-intercept
        tag_with_ref: true
        tag_with_sha: true
